### ISSUE TITLE
Feature request: Send s-expr to REPL

### ISSUE THREAD

**Issue by grierson** [mauricioszabo/repl-tooling#102]
I would like to send current code block or top code block to my connected REPL and eval there instead of sending to the Clover REPL
So that I can leverage rebel-readline

Expect:
(+ 1 1|) ;; Send top code block to repl
=> 2 ;; REPL running in term

Thank you! (Love the project <3)

**Comment by mauricioszabo** [comment]
Hi, unfortunately that's not possible. The REPL you see on your term is not the same as Chlorine/Clover connects to. This projects connects to a Socket REPL (all communication is made via socket) so there's no way to do it.

What you can do is to send commands via tmux. It's the same approach I use on another plug-in: https://github.com/mauricioszabo/atom-tmux-terminal (only for Atom editor), so maybe you can find something for VSCode that will send forms / blocks of text / selections to a tmux terminal...
