### ISSUE TITLE
Where is (is it?) the clojure-plus.repl dep specified ?

### ISSUE THREAD

**Issue by birdspider** [mauricioszabo/repl-tooling#12]
Is there a dep missing ?

Attempting to build atom-chlorine:

```
lein run -m shadow.cljs.devtools.cli --npm release npm
[:npm] Compiling ...
The required namespace "clojure-plus.repl" is not available, 
    it was required by "repl_tooling/features/documentation.cljs".
```

used in: [src/repl_tooling/features/documentation.cljs#L2](https://github.com/mauricioszabo/repl-tooling/blob/master/src/repl_tooling/features/documentation.cljs#L2) 

EDIT: or am I just confused because:
_atom-chlorine_ depends on _repl-tooling_ which depends on _clojure-plus.repl_ which is part of _clojure-plus_ which depends on _proto-repl_, which (according to this [blogpost](http://corfield.org/blog/2018/12/19/atom-chlorine/)) can be disabled.

**Comment by mauricioszabo** [comment]
There are still some issues which leads to this confusion :)

This package is being developed together with Chlorine. Chlorine was based on an old plugin called `clojure-plus`. Every place where `clojure-plus` appears can be considered deprecated and needs to be removed (I even though that it already was... anyway). 

The idea is that Chlorine depends on this package, and this package have no dependencies whatsoever.  I'll look into this issue (when developing a new feature from Chlorine I inadvertently created a circular dependency).
